name: Static Analysis

on:
  workflow_run:
    workflows: ["Duster Fix"]
    types:
      - completed

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6
    - uses: php-actions/phpstan@v3
      with:
        path: app/
