name: tests

on:
  pull_request:
    branches: [development, dev, acceptance, staging, main, master]

jobs:
  skip-duplicates:
    continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-latest

    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}

    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          # All of these options are optional, so you can remove them if you are happy with the defaults
          cancel_others: "true"
          concurrent_skipping: "same_content"
          skip_after_successful_duplicate: "true"
          paths_ignore: '["**/README.md", "**/docs/**"]'

  workbench-tests:
    needs: skip-duplicates
    if: needs.skip-duplicates.outputs.should_skip != 'true'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"

      - uses: php-actions/composer@v6

      - name: Directory Permissions
        run: sudo chown -R $(whoami) vendor/orchestra/testbench-core/laravel

      - name: Execute tests
        run: ./vendor/bin/testbench package:test --bail --retry
